# Generated by Django 3.2.18 on 2023-04-02 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_replycomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='login_require',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ReplyComment',
        ),
    ]
